[build]
  publish = ".next"
  command = "npm run build"

# Enable Next.js Runtime for API routes support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Your environment variables
# [build.environment]
#   NEXT_PUBLIC_API_URL = "http://localhost:3000"
#   MONGODB_URI = "mongodb+srv://admin:admin@cluster0.oplpgp2.mongodb.net/clensy-cms"